
server:
  port: 9090
spring:
  application:
    name: web-01
  datasource:
    url: jdbc:mysql://localhost:3306/eticaret?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

